"""Doctor and Patient Management REST API.

A small, beginner-friendly FastAPI application. Data is kept in memory
using plain Python dictionaries, so everything is lost when the server
stops - that is intentional for this first version.

Run it with:  uvicorn main:app --reload
Swagger UI:    http://127.0.0.1:8000/docs
ReDoc:         http://127.0.0.1:8000/redoc
"""

from itertools import count
from typing import Any, Dict, List

from fastapi import FastAPI, HTTPException, status

from models import DoctorCreate, PatientCreate
from schemas import Doctor, Patient

app = FastAPI(
    title="Doctor and Patient Management API",
    description=(
        "A simple REST API for managing doctors and patients.\n\n"
        "* **Doctors** can be created, listed and fetched by id.\n"
        "* **Patients** can be created and listed.\n\n"
        "Data is stored in memory only."
    ),
    version="1.0.0",
)

# ---------------------------------------------------------------------------
# In-memory storage. In a real app this would be replaced by a database.
# ---------------------------------------------------------------------------
doctors: Dict[int, Dict[str, Any]] = {}
patients: Dict[int, Dict[str, Any]] = {}

# Counters used to generate unique ids.
_doctor_ids = count(start=1)
_patient_ids = count(start=1)


# ---------------------------------------------------------------------------
# Doctor endpoints
# ---------------------------------------------------------------------------
@app.post(
    "/doctors",
    response_model=Doctor,
    status_code=status.HTTP_201_CREATED,
    tags=["Doctors"],
    summary="Create a new doctor",
)
def create_doctor(payload: DoctorCreate) -> Dict[str, Any]:
    """Create a doctor. The ``doctor_id`` is generated by the server."""
    doctor_id = next(_doctor_ids)
    doctor = {
        "doctor_id": doctor_id,
        "name": payload.name,
        "specialization": payload.specialization,
        "email": str(payload.email),
        "is_active": payload.is_active,
    }
    doctors[doctor_id] = doctor
    return doctor


@app.get(
    "/doctors",
    response_model=List[Doctor],
    tags=["Doctors"],
    summary="List all doctors",
)
def list_doctors() -> List[Dict[str, Any]]:
    """Return every doctor, or an empty list if none exist."""
    return list(doctors.values())


@app.get(
    "/doctors/{doctor_id}",
    response_model=Doctor,
    tags=["Doctors"],
    summary="Get a doctor by id",
)
def get_doctor(doctor_id: int) -> Dict[str, Any]:
    """Return a single doctor, or 404 if the id is unknown."""
    doctor = doctors.get(doctor_id)
    if doctor is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Doctor not found",
        )
    return doctor


# ---------------------------------------------------------------------------
# Patient endpoints
# ---------------------------------------------------------------------------
@app.post(
    "/patients",
    response_model=Patient,
    status_code=status.HTTP_201_CREATED,
    tags=["Patients"],
    summary="Create a new patient",
)
def create_patient(payload: PatientCreate) -> Dict[str, Any]:
    """Create a patient. The ``patient_id`` is generated by the server."""
    patient_id = next(_patient_ids)
    patient = {
        "patient_id": patient_id,
        "name": payload.name,
        "age": payload.age,
        "phone": payload.phone,
    }
    patients[patient_id] = patient
    return patient


@app.get(
    "/patients",
    response_model=List[Patient],
    tags=["Patients"],
    summary="List all patients",
)
def list_patients() -> List[Dict[str, Any]]:
    """Return every patient, or an empty list if none exist."""
    return list(patients.values())


if __name__ == "__main__":
    import uvicorn

    uvicorn.run("main:app", host="127.0.0.1", port=8000, reload=True)