"""Response models (output schemas).

These Pydantic models describe the JSON the API sends back to the client.
Using ``response_model=`` gives you two things for free:

* the output is filtered and validated before it leaves the server;
* Swagger UI documents the exact shape of every response.
"""

from pydantic import BaseModel, EmailStr, Field


class Doctor(BaseModel):
    """A doctor record as returned by the API."""

    doctor_id: int = Field(..., description="Unique id, generated by the server", examples=[1])
    name: str = Field(..., examples=["Dr. Ada Lovelace"])
    specialization: str = Field(..., examples=["Cardiology"])
    email: EmailStr = Field(..., examples=["ada.lovelace@example.com"])
    is_active: bool = Field(..., examples=[True])


class Patient(BaseModel):
    """A patient record as returned by the API."""

    patient_id: int = Field(..., description="Unique id, generated by the server", examples=[1])
    name: str = Field(..., examples=["Grace Hopper"])
    age: int = Field(..., examples=[36])
    phone: str = Field(..., examples=["+1-555-0100"])